version: '3'

services:
  opendb_adapter:
    image: covenantsql/covenantsql:latest
    container_name: opendb_adapter
    restart: always
    ports:
      - '11105:4661'
    environment:
      COVENANT_ROLE: adapter
      COVENANT_CONF: ./node_adapter/config.yaml
      COVENANTSQL_ADAPTER_ADDR: 0.0.0.0:4661
    volumes:
      - ./test/service_split/node_adapter/:/app/node_adapter/
    networks:
      default:
        ipv4_address: 172.254.1.8
  opendb_mysql_adapter:
    image: covenantsql/covenantsql:latest
    container_name: opendb_mysql_adapter
    restart: always
    ports:
      - '11107:4664'
    command: ['-listen', '0.0.0.0:4664']
    environment:
      COVENANT_ROLE: mysql-adapter
      COVENANT_CONF: ./node_mysql_adapter/config.yaml
    volumes:
      - ./test/service_split/node_mysql_adapter/:/app/node_mysql_adapter/
    networks:
      default:
        ipv4_address: 172.254.1.10
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  opendb_explorer:
    image: covenantsql/covenantsql:latest
    container_name: opendb_explorer
    restart: always
    ports:
      - '11108:4663'
    environment:
      COVENANT_ROLE: explorer
      COVENANT_CONF: ./node_explorer/config.yaml
      COVENANTSQL_OBSERVER_ADDR: 0.0.0.0:4663
    volumes:
      - ./test/service_split/node_explorer/:/app/node_explorer/
    networks:
      default:
        ipv4_address: 172.254.1.9
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
  opendb_fullnode:
    image: covenantsql/covenantsql:latest
    container_name: opendb_fullnode
    restart: always
    ports:
      - '11110:8546'
    command: ['-wsapi', ':8546']
    # entrypoint: ["sh"]
    environment:
      COVENANT_ROLE: blockproducer
      COVENANT_CONF: ./fullnode_0/config.yaml
    volumes:
      - ./test/service_split/fullnode_0/:/app/fullnode_0/
    networks:
      default:
        ipv4_address: 172.254.1.11
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.254.1.0/24
