version: '3'

services:
  node_00:
    image: covenantsql/covenantsql:latest
    container_name: node_00
    restart: always
    ports:
      - '12100:4661'
      - '12101:4665'
    expose:
      - "12100"      
      - "12101"
    environment:
      COVENANT_ROLE: blockproducer
      COVENANT_CONF: ./node_0/config.yaml
      # METRIC_WEB_ADDR: '0.0.0.0:4665'
    volumes:
      - ./test/service_split/node_0/:/app/node_0/
    networks:
      default:
        ipv4_address: 172.254.1.2
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
  opendb_fullnode:
    image: covenantsql/covenantsql:latest
    container_name: opendb_fullnode
    restart: always
    ports:
      - '11110:8546'
    expose:
      - "11110"
    command: ['-wsapi', ':8546', "-log-level", "debug"]
    # entrypoint: ["sh"]
    environment:
      COVENANT_ROLE: blockproducer
      COVENANT_CONF: ./fullnode_0/config.yaml
    volumes:
      - ./test/service_split/fullnode_0/:/app/fullnode_0/
    networks:
      default:
        ipv4_address: 172.254.1.11
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.254.1.0/24
